apiVersion: apps/v1
kind: Deployment
metadata:
  name: Prometheus-deployment
  labels:
    app: Prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Prometheus
  template:
    metadata:
      labels:
        app: Prometheus
    spec:
      containers:
        - name: Prometheus-container
          image: Prometheus-image:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR_NAME
              value: "value"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
